services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    container_name: resume-builder-tunnel
    restart: unless-stopped
    environment:
      NODE_ENV: production

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: resume-builder-cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TUNNEL_TOKEN}
    depends_on:
      - app
